//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Baseevent struct {
	ID            string `sql:"primary_key"`
	Title         string
	About         string
	UniversityID  string
	PostTime      time.Time
	StartTime     time.Time
	ContactPhone  string
	ContactEmail  string
	EventLocation string
}
