//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Baseevent struct {
	ID           string `sql:"primary_key"`
	Title        string
	About        string
	UniversityID string
	StartTime    time.Time
	ContactPhone string
	ContactEmail string
	Latitude     float64
	Longitude    float64
}
