//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type Rating struct {
	ID          string `sql:"primary_key"`
	Stars       int32
	StudentID   *string
	BaseEventID string
}
