//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type Rsomember struct {
	ID      string `sql:"primary_key"`
	RsoID   string `sql:"primary_key"`
	IsAdmin bool
}
