//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type Taggedrso struct {
	TagID string `sql:"primary_key"`
	RsoID string `sql:"primary_key"`
}
