// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package gen_sql

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Baseevent struct {
	ID           string           `schema:",required"`
	Title        string           `schema:",required"`
	About        string           `schema:",required"`
	University   string           `schema:",required"`
	StartTime    pgtype.Timestamp `schema:",required"`
	ContactPhone string           `schema:",required"`
	ContactEmail string           `schema:",required"`
	EventType    string           `schema:",required"`
	Latitude     float64          `schema:",required"`
	Longitude    float64          `schema:",required"`
}

type Baseuser struct {
	ID           string      `schema:",required"`
	NameFirst    string      `schema:",required"`
	NameLast     string      `schema:",required"`
	Email        string      `schema:",required"`
	PasswordHash string      `schema:",required"`
	IsSuperAdmin bool        `schema:",required"`
	University   pgtype.Text `schema:",required"`
}

type Comment struct {
	ID        string      `schema:",required"`
	Body      string      `schema:",required"`
	PostedBy  pgtype.Text `schema:",required"`
	BaseEvent string      `schema:",required"`
}

type Rating struct {
	ID        string      `schema:",required"`
	Stars     int32       `schema:",required"`
	PostedBy  pgtype.Text `schema:",required"`
	BaseEvent string      `schema:",required"`
}

type Rso struct {
	ID         string `schema:",required"`
	Title      string `schema:",required"`
	About      string `schema:",required"`
	University string `schema:",required"`
}

type Rsomember struct {
	ID      string `schema:",required"`
	Rso     string `schema:",required"`
	IsAdmin bool   `schema:",required"`
}

type Tag struct {
	ID    string `schema:",required"`
	Title string `schema:",required"`
}

type Taggedevent struct {
	Tag       string `schema:",required"`
	BaseEvent string `schema:",required"`
}

type Taggedrso struct {
	Tag string `schema:",required"`
	Rso string `schema:",required"`
}

type University struct {
	ID        string  `schema:",required"`
	Title     string  `schema:",required"`
	Latitude  float64 `schema:",required"`
	Longitude float64 `schema:",required"`
	About     string  `schema:",required"`
}
