// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package gen_sql

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Comment struct {
	ID              int32
	Body            string
	PostedBy        pgtype.Int4
	UniversityEvent int32
}

type Coordinate struct {
	ID        int32
	Title     string
	Latitude  float64
	Longitude float64
}

type Privateevent struct {
	ID int32
}

type Publicevent struct {
	ID       int32
	Approved bool
}

type Rating struct {
	ID              int32
	Stars           int32
	PostedBy        pgtype.Int4
	UniversityEvent int32
}

type Rso struct {
	ID         int32
	Title      string
	University int32
}

type Rsoevent struct {
	ID  int32
	Rso int32
}

type Rsomember struct {
	Rso              int32
	UniversityMember int32
	IsAdmin          bool
}

type Superadmin struct {
	ID int32
}

type Tag struct {
	ID   int32
	Name string
}

type Taggedevent struct {
	Tag             int32
	UniversityEvent int32
}

type Taggedrso struct {
	Tag int32
	Rso int32
}

type University struct {
	ID         int32
	Title      string
	Coordinate int32
	About      string
}

type Universityevent struct {
	ID                 int32
	Title              string
	Body               string
	University         int32
	OccurrenceTime     pgtype.Timestamp
	OccurrenceLocation int32
	ContactPhone       string
	ContactEmail       string
}

type Universitymember struct {
	ID           int32
	University   int32
	NameFirst    string
	NameMiddle   string
	NameLast     string
	Email        string
	PasswordHash string
}
