//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Privateevent = newPrivateeventTable("cew", "privateevent", "")

type privateeventTable struct {
	postgres.Table

	// Columns
	ID postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type PrivateeventTable struct {
	privateeventTable

	EXCLUDED privateeventTable
}

// AS creates new PrivateeventTable with assigned alias
func (a PrivateeventTable) AS(alias string) *PrivateeventTable {
	return newPrivateeventTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new PrivateeventTable with assigned schema name
func (a PrivateeventTable) FromSchema(schemaName string) *PrivateeventTable {
	return newPrivateeventTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new PrivateeventTable with assigned table prefix
func (a PrivateeventTable) WithPrefix(prefix string) *PrivateeventTable {
	return newPrivateeventTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new PrivateeventTable with assigned table suffix
func (a PrivateeventTable) WithSuffix(suffix string) *PrivateeventTable {
	return newPrivateeventTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newPrivateeventTable(schemaName, tableName, alias string) *PrivateeventTable {
	return &PrivateeventTable{
		privateeventTable: newPrivateeventTableImpl(schemaName, tableName, alias),
		EXCLUDED:          newPrivateeventTableImpl("", "excluded", ""),
	}
}

func newPrivateeventTableImpl(schemaName, tableName, alias string) privateeventTable {
	var (
		IDColumn       = postgres.StringColumn("id")
		allColumns     = postgres.ColumnList{IDColumn}
		mutableColumns = postgres.ColumnList{}
	)

	return privateeventTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID: IDColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
