//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Rso = newRsoTable("cew", "rso", "")

type rsoTable struct {
	postgres.Table

	// Columns
	ID           postgres.ColumnString
	Title        postgres.ColumnString
	About        postgres.ColumnString
	UniversityID postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type RsoTable struct {
	rsoTable

	EXCLUDED rsoTable
}

// AS creates new RsoTable with assigned alias
func (a RsoTable) AS(alias string) *RsoTable {
	return newRsoTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new RsoTable with assigned schema name
func (a RsoTable) FromSchema(schemaName string) *RsoTable {
	return newRsoTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new RsoTable with assigned table prefix
func (a RsoTable) WithPrefix(prefix string) *RsoTable {
	return newRsoTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new RsoTable with assigned table suffix
func (a RsoTable) WithSuffix(suffix string) *RsoTable {
	return newRsoTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newRsoTable(schemaName, tableName, alias string) *RsoTable {
	return &RsoTable{
		rsoTable: newRsoTableImpl(schemaName, tableName, alias),
		EXCLUDED: newRsoTableImpl("", "excluded", ""),
	}
}

func newRsoTableImpl(schemaName, tableName, alias string) rsoTable {
	var (
		IDColumn           = postgres.StringColumn("id")
		TitleColumn        = postgres.StringColumn("title")
		AboutColumn        = postgres.StringColumn("about")
		UniversityIDColumn = postgres.StringColumn("university_id")
		allColumns         = postgres.ColumnList{IDColumn, TitleColumn, AboutColumn, UniversityIDColumn}
		mutableColumns     = postgres.ColumnList{TitleColumn, AboutColumn, UniversityIDColumn}
	)

	return rsoTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:           IDColumn,
		Title:        TitleColumn,
		About:        AboutColumn,
		UniversityID: UniversityIDColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
