//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Student = newStudentTable("cew", "student", "")

type studentTable struct {
	postgres.Table

	// Columns
	ID           postgres.ColumnString
	UniversityID postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type StudentTable struct {
	studentTable

	EXCLUDED studentTable
}

// AS creates new StudentTable with assigned alias
func (a StudentTable) AS(alias string) *StudentTable {
	return newStudentTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new StudentTable with assigned schema name
func (a StudentTable) FromSchema(schemaName string) *StudentTable {
	return newStudentTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new StudentTable with assigned table prefix
func (a StudentTable) WithPrefix(prefix string) *StudentTable {
	return newStudentTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new StudentTable with assigned table suffix
func (a StudentTable) WithSuffix(suffix string) *StudentTable {
	return newStudentTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newStudentTable(schemaName, tableName, alias string) *StudentTable {
	return &StudentTable{
		studentTable: newStudentTableImpl(schemaName, tableName, alias),
		EXCLUDED:     newStudentTableImpl("", "excluded", ""),
	}
}

func newStudentTableImpl(schemaName, tableName, alias string) studentTable {
	var (
		IDColumn           = postgres.StringColumn("id")
		UniversityIDColumn = postgres.StringColumn("university_id")
		allColumns         = postgres.ColumnList{IDColumn, UniversityIDColumn}
		mutableColumns     = postgres.ColumnList{UniversityIDColumn}
	)

	return studentTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:           IDColumn,
		UniversityID: UniversityIDColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
