//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

// UseSchema sets a new schema name for all generated table SQL builder types. It is recommended to invoke
// this method only once at the beginning of the program.
func UseSchema(schema string) {
	Baseevent = Baseevent.FromSchema(schema)
	Baseuser = Baseuser.FromSchema(schema)
	Comment = Comment.FromSchema(schema)
	Privateevent = Privateevent.FromSchema(schema)
	Publicevent = Publicevent.FromSchema(schema)
	Rating = Rating.FromSchema(schema)
	Rso = Rso.FromSchema(schema)
	Rsoevent = Rsoevent.FromSchema(schema)
	Rsomember = Rsomember.FromSchema(schema)
	Student = Student.FromSchema(schema)
	Superadmin = Superadmin.FromSchema(schema)
	Tag = Tag.FromSchema(schema)
	Taggedevent = Taggedevent.FromSchema(schema)
	Taggedrso = Taggedrso.FromSchema(schema)
	University = University.FromSchema(schema)
}
