//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Taggedrso = newTaggedrsoTable("cew", "taggedrso", "")

type taggedrsoTable struct {
	postgres.Table

	// Columns
	TagID postgres.ColumnString
	RsoID postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type TaggedrsoTable struct {
	taggedrsoTable

	EXCLUDED taggedrsoTable
}

// AS creates new TaggedrsoTable with assigned alias
func (a TaggedrsoTable) AS(alias string) *TaggedrsoTable {
	return newTaggedrsoTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new TaggedrsoTable with assigned schema name
func (a TaggedrsoTable) FromSchema(schemaName string) *TaggedrsoTable {
	return newTaggedrsoTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new TaggedrsoTable with assigned table prefix
func (a TaggedrsoTable) WithPrefix(prefix string) *TaggedrsoTable {
	return newTaggedrsoTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new TaggedrsoTable with assigned table suffix
func (a TaggedrsoTable) WithSuffix(suffix string) *TaggedrsoTable {
	return newTaggedrsoTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newTaggedrsoTable(schemaName, tableName, alias string) *TaggedrsoTable {
	return &TaggedrsoTable{
		taggedrsoTable: newTaggedrsoTableImpl(schemaName, tableName, alias),
		EXCLUDED:       newTaggedrsoTableImpl("", "excluded", ""),
	}
}

func newTaggedrsoTableImpl(schemaName, tableName, alias string) taggedrsoTable {
	var (
		TagIDColumn    = postgres.StringColumn("tag_id")
		RsoIDColumn    = postgres.StringColumn("rso_id")
		allColumns     = postgres.ColumnList{TagIDColumn, RsoIDColumn}
		mutableColumns = postgres.ColumnList{}
	)

	return taggedrsoTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		TagID: TagIDColumn,
		RsoID: RsoIDColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
